// Generated by scripts/copy-wllama-assets.mjs. Do not edit by hand.
export const wllamaRuntimeAssets = {
  script: "/runtime/wllama/index.0d9b01f0.js",
  defaultWasm: "/runtime/wllama/wllama.4197ce6d.wasm",
  compatWasm: "/runtime/wllama/compat.9ea153d9.wasm",
  compatWorker: "/runtime/wllama/compat-worker.011e11f2.js",
} as const;
